name: Pop-Gen-Pipe
channels:
  - conda-forge
  - bioconda
dependencies:
  - git=2.53.0
  - cxx-compiler=1.11.0
  - cmake=4.2.3
  - python>=3.8
  - r-base
  - r-essentials
  - scipy
  - numpy
  - matplotlib
  - r-poppr
  - r-adegenet
  - r-vcfr
  - r-tidyverse
  - r-cowplot
  - r-ape
  - r-vegan
  - r-hierfstat
  - r-ecodist
  - r-diversity
  - r-graph4lg
  - pip
  - pandas
  - pyyaml
  - r-ggplot2
  - r-optparse
