#!/usr/bin/bash

# A script connecting population genetics analyses in R.
conda activate Pop-Gen-PipeEnv

# create a directory where you want your output files to go
mkdir pop-gen-pipeline

# activate R
R

# libraries
library(poppr)

# grab 3 files from populations output (Created from STACKS): "populations.haps.gen" and "populations.snps.gen" from your multiple
# SNPs per locus and "populations.snps.gen" from single SNP per locus. NOTE: these files have the same
# name in populations output! Rename to match below.
haps.infile_gen = "populations.haps.gen"
multiple.infile_gen = "populations.snps.multi.gen"
single.infile_gen = "populations.snps.single.gen"

# Convert genind objects to readable genepop text files
haps.infile = genind_to_genepop(haps.infile_gen)
multiple.infile = genind_to_genepop(haps.infile_gen)
single.infile = genind_to_genepop(haps.single.infile)

# add genepop converter

# AMOVA

# Read in data from Multiple SNPs per locus haps.gen file

geneid.nout = read.genepop("populations.haps.gen")

# Convert genind object to a genclone object

genclone.nout<-as.genclone(geneid.nout)

# Amend individual names to assign them to a specific population

strata(genclone.nout)<-(as.data.frame(geneid.nout$pop))


##AMOVA

genclone.nout
genclone.nout$strata
site.amova.pop = poppr.amova(genclone.nout, ~geneid.n>

####Print Results

site.amova.pop

##Randomization Test
site.amova.pop.rtest<-randtest(coosaensis.site.amova.pop,nrepet = 999)
site.amova.pop.rtest
plot(site.amova.pop.rtest)

#
